# Generated by Django 6.1.1 on 2026-09-15 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refinement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='refinement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
